[package]
name = "day07a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cards="1.1.2"
clap = { version = "4", features = ["derive", "env"] }
combine = "4"
itertools = "0.12.0"