[package]
name = "day13b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
combine = "4"
ndarray = "0.15.6"
num="0.4.1"